using System;
using System.Collections.Generic;
using System.Text;

namespace RandomSkillsSurvivor
{
    public enum MySkillIndex : int
    {
        SkillIndex_Enrage = 0, // no
        SkillIndex_Rain = 1, // no
        SkillIndex_RHCanon = 2, // no
        SkillIndex_Cannons1 = 3, // maybe
        SkillIndex_FireGrenade1 = 4,
        SkillIndex_PlaceMine1 = 5, // No
        SkillIndex_Unnamed1 = 6, // triple tele
        SkillIndex_Gun1 = 7, // not enough damage
        SkillIndex_Gun2 = 8, // no
        SkillIndex_Cloak = 9, // bandit
        SkillIndex_FireShotgun = 10,
        SkillIndex_Grenade = 11, // no 
        SkillIndex_LightsOut = 12,
        SkillIndex_Headbutt1 = 13, // no 
        SkillIndex_Sleep = 14, // no 
        SkillIndex_DefenseUp = 15, // no 
        SkillIndex_GroundSlam = 16, // no 
        SkillIndex_Sunder = 17, // no 
        SkillIndex_SpawnWards = 18, // no 
        SkillIndex_Spit = 19, // needs to be rewoked
        SkillIndex_SummonEggs = 20,
        SkillIndex_BellBlast = 21,  // no 
        SkillIndex_Charge = 22, // no 
        SkillIndex_Headbutt2 = 23,
        SkillIndex_FireBarrage1 = 24, // no
        SkillIndex_FireRocket = 25, // needs more damage
        SkillIndex_PaintMicroMissiles = 26,
        SkillIndex_Roll1 = 27,
        SkillIndex_Leap1 = 28,
        SkillIndex_SwipeForward = 29,
        SkillIndex_Charge_Bombardment = 30,
        SkillIndex_Recover = 31,
        SkillIndex_Tarball = 32,
        SkillIndex_Gun3 = 33,
        SkillIndex_Knockback = 34,
        SkillIndex_Barrage = 35,
        SkillIndex_FireFMJ1 = 36,
        SkillIndex_FirePistol1 = 37,
        SkillIndex_FireShotgunBlast = 38,
        SkillIndex_Roll2 = 39,
        SkillIndex_SweepBarrage = 40,
        SkillIndex_ThrowGrenade = 41,
        SkillIndex_Barrage1 = 42,
        SkillIndex_FireFMJ2 = 43,
        SkillIndex_FirePistol2 = 44,
        SkillIndex_Roll3 = 45,
        SkillIndex_CrocoChainableLeap = 46,
        SkillIndex_CrocoDisease = 47,
        SkillIndex_CrocoLeap = 48,
        SkillIndex_CrocoSlash = 49,
        SkillIndex_CrocoPoison = 50,
        SkillIndex_Gun4 = 51,
        SkillIndex_HealingBeam = 52,
        SkillIndex_Blink = 53,
        SkillIndex_StanceSwitch1 = 54,
        SkillIndex_StartHealBeam = 55,
        SkillIndex_FireBarrage2 = 56,
        SkillIndex_FireFMJ3 = 57,
        SkillIndex_FirePistol3 = 58,
        SkillIndex_Roll4 = 59,
        SkillIndex_Turret1 = 60,
        SkillIndex_FireGrenade2 = 61,
        SkillIndex_PlaceBubbleShield = 62,
        SkillIndex_PlaceMine2 = 63,
        SkillIndex_PlaceSpiderMine = 64,
        SkillIndex_PlaceTurret = 65,
        SkillIndex_PlaceWalkerTurret = 66,
        SkillIndex_ThrowMineDeployer = 67,
        SkillIndex_Turret2 = 68,
        SkillIndex_Turret3 = 69,
        SkillIndex_Flamethrower1 = 70,
        SkillIndex_Clap = 71,
        SkillIndex_Laser1 = 72,
        SkillIndex_Barrage2 = 73,
        SkillIndex_PrepHook = 74,
        SkillIndex_Cannons2 = 75,
        SkillIndex_Fire_Winch = 76,
        SkillIndex_FullSwing = 77,
        SkillIndex_Overclock = 78,
        SkillIndex_Slam = 79,
        SkillIndex_BurrowMortar = 80,
        SkillIndex_AimArrowSnipe = 81,
        SkillIndex_FireArrowSnipe = 82,
        SkillIndex_ArrowRain = 83,
        SkillIndex_Blink1 = 84,
        SkillIndex_FireSeekingArrow = 85,
        SkillIndex_Glaive = 86,
        SkillIndex_Blink2 = 87,
        SkillIndex_Blink3 = 88,
        SkillIndex_DoubleSlash = 89,
        SkillIndex_Blink4 = 90,
        SkillIndex_FireVoidspikes = 91,
        SkillIndex_GroundPound = 92,
        SkillIndex_Nova = 93,
        SkillIndex_Bite = 94,
        SkillIndex_Fireball = 95, // no
        SkillIndex_Unnamed4 = 96,// maybe
        SkillIndex_Unnamed5 = 97,
        SkillIndex_Overcharge = 98,
        SkillIndex_Unnamed6 = 99,
        SkillIndex_ChargeFist = 100,
        SkillIndex_ChargeZapFist = 101,
        SkillIndex_FireHook1 = 102,
        SkillIndex_FireYankHook = 103,
        SkillIndex_Unnamed7= 104,
        SkillIndex_LoaderSatellite = 105,
        SkillIndex_LunarPrimaryReplacement = 106,
        SkillIndex_LunarUtilityReplacement = 107,
        SkillIndex_FireFirebolt = 108,
        SkillIndex_FireIceBolt = 109,
        SkillIndex_FireLightningBolt = 110,
        SkillIndex_Flamethrower2 = 111,
        SkillIndex_FlyUp = 112,
        SkillIndex_IceBomb = 113,
        SkillIndex_NovaBomb = 114,
        SkillIndex_Wall = 115,
        SkillIndex_Blink5 = 116,
        SkillIndex_StanceSwitch2 = 117,
        SkillIndex_Gun5 = 118,
        SkillIndex_Rocket1 = 119,
        SkillIndex_Dash1 = 120,
        SkillIndex_Evis1 = 121,
        SkillIndex_Evis2 = 122,
        SkillIndex_GroundLight = 123,
        SkillIndex_Uppercut = 124,
        SkillIndex_Whirlwind = 125,
        SkillIndex_Gun6 = 126,
        SkillIndex_FireNull = 127,
        SkillIndex_BarrierUp = 128,
        SkillIndex_Leap2 = 129,
        SkillIndex_Rocket2 = 130,
        SkillIndex_FireCannon1 = 131,
        SkillIndex_FireCannon2 = 132,
        SkillIndex_Cannons3 = 133,
        SkillIndex_Cannons4 = 134,
        SkillIndex_Eyeblast = 135,
        SkillIndex_DelayKnockup = 136,
        SkillIndex_SuperEyeblast = 137,
        SkillIndex_SuperDelayKnockup = 138,
        SkillIndex_Turret4 = 139,
        SkillIndex_Unnamed8 = 140, // no
        SkillIndex_Unnamed9 = 141,
        SkillIndex_Unnamed10 = 142,
        SkillIndex_Unnamed11 = 143,
        SkillIndex_KickFromShop = 144,
        SkillIndex_FireFMJ4 = 145,
        SkillIndex_FireRifle = 146,
        SkillIndex_Reload = 147,
        SkillIndex_Roll = 148,
        SkillIndex_LockOn = 149,
        SkillIndex_TurretGun = 150,
        SkillIndex_Fist = 151,
        SkillIndex_Laser2 = 152,
        SkillIndex_RechargeRocks = 153,
        SkillIndex_ChargeGoldLaser = 154, // no
        SkillIndex_FireGoldFist = 155, // no
        SkillIndex_FireBuzzsaw = 156,
        SkillIndex_FireGrenadeLauncher = 157,
        SkillIndex_FireNailgun = 158,
        SkillIndex_FireSpear = 159,
        SkillIndex_StunDrone = 160,
        SkillIndex_Swap = 161,
        SkillIndex_ToolbotDash = 162,
        SkillIndex_AimMortar2 = 163,
        SkillIndex_AimMortarRain = 164,
        SkillIndex_FireFlower2 = 165,
        SkillIndex_FireSyringe = 166,
        SkillIndex_SonicBoom2 = 167,
        SkillIndex_SonicBoom = 168,
        SkillIndex_SonicPull = 169,
        SkillIndex_TurretGun1 = 170, // no
        SkillIndex_TurretGun2 = 171, // no
        SkillIndex_ChargeMegaNova = 172,
        SkillIndex_JellyBarrage = 173,
        SkillIndex_TrackingBomb = 174,
        SkillIndex_ChargeWindblade = 175,
        SkillIndex_Fly = 176,
        SkillIndex_Unnamed12 = 177,
        SkillIndex_FireEmber = 178,
    }
}
